AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a Lambada function that can queries a DynamoDB table 

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    
    
Parameters:
  Project:
    Type: String
    Default: GraphQL
    Description: Name of the project. Used in the tags.

Resources:
  GraphQLFunctionRole:
    Type: AWS::IAM::Role
    Properties: 
      Description: Allows permission to scan the DynamoDB table.
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Sid: AllowLambdaServiceToAssumeRole
            Effect: Allow
            Action: 
              - sts:AssumeRole
            Principal:
              Service: 
                - lambda.amazonaws.com
      Policies:
        -
          PolicyName: GraphQLFunctionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action: 
                - dynamodb:Scan
                - dynamodb:PutItem
                - dynamodb:DeleteItem
              Resource: 
                - !GetAtt TasksDynamoDBTable.Arn
                - !GetAtt CategoriesDynamoDBTable.Arn

  GraphQLFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName:
        !Sub
        - ${Project}-query-function-${Id}
        - Project: !Ref Project
          Id: !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]] 
      CodeUri: API/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt GraphQLFunctionRole.Arn
      Architectures:
        - x86_64
      Description: API endpoint that queries DynamoDB 
      Environment:
        Variables:
          TASKS_TABLE: !Ref TasksDynamoDBTable
          CATEGORIES_TABLE: !Ref CategoriesDynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: any
            RestApiId:
              Ref: ApiGatewayApi
    
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: graphql
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
      EndpointConfiguration:
        Type: REGIONAL
            
  TasksDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName:
        !Sub
        - ${Project}-tasks-table-${Id}
        - Project: !Ref Project
          Id: !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AttributeDefinitions:
        -
          AttributeName: category
          AttributeType: S
        - 
          AttributeName: id
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: category
          KeyType: HASH
        - 
          AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 30
        WriteCapacityUnits: 30
      Tags:
        - Key: Project
          Value: !Ref Project
          
  CategoriesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName:
        !Sub
        - ${Project}-categories-table-${Id}
        - Project: !Ref Project
          Id: !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 30
        WriteCapacityUnits: 30
      Tags:
        - Key: Project
          Value: !Ref Project